.\" Copyright 2024 Tpaefawzen
.\" 
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\" 
.\" THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
.\" REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
.\" FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
.\" INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
.\" LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
.\" OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.Dd March 31, 2024
.Dt DIS-ESOLANG 1
.Os
.Sh NAME
.Nm dis-esolang
.Nd Optimized interpreter for esoteric programming language Dis
.Sh SYNOPSIS
.Nm
.Op Fl \&Ev
.Op Fl k Ar STEPS
.Ar FILE
.Sh DESCRIPTION
The
.Nm
reads a program source for esoteric programming language Dis, then
interpret and run using standard input and standard output.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl E
Allow any non-command characters to load.
.It Fl v
Enable verbose mode; print debugging information to standard error.
.It Fl k Ar STEPS
Run the Dis program for given
.Ar STEPS .
In this mode exit status indicates whether program has halt.
.El
.Pp
I have implemented signal handling for
.Dv SIGHUP ,
.Dv SIGINT ,
.Dv SIGQUIT ,
.Dv SIGPIPE ,
.Dv SIGALRM ,
and
.Dv SIGTERM ;
when
.Nm
catches one of those signals it cleans up dynamically allocated
memory.
.Sh EXIT STATUS
.Ex -std
However when
.Fl k
is given the
.Nm
utility exits\~0 on success and program halted,
and\~>0 if success but program still running, or an error error
occurs.
.Sh REPOSITORY
.Lk https://github.com/Tpaefawzen/dis.optimized \
 "Available on Tpaefawzen/dis.optimized on GitHub"
.Sh SEE ALSO
.Lk https://esolangs.org/wiki/Dis "Dis \(hy Esolang"
